### Importação de Bibliotecas

In [1]:
#Codigo para importar as bibliotecas que serão utilizadas na Analise
import pandas as pd
import numpy as np

### Analise Exploratória

In [2]:
# Utilizando a biblioteca Pandas para carregar o arquivo em formato CSV para um DataFrame.
 
df = pd.read_csv("base_varejo.csv", sep=";")

In [3]:
#Mostra as 5 primeiras linhas do DataFrame
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [4]:
#Apresenta as ultimass 5 linhas do DataFrame
df.tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [5]:
#Comando para apresentar 10 amostras aleatorias de linhas do DataFrame
df.sample(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
523373,31/05/2021,576433,615,M,1,4,C,90,HIGIENE,SHAMPOO,NaN,NaN,NaN,NaN
299882,06/03/2020,333841,639,M,2,0,C,132,HIGIENE,SABONETE,NaN,NaN,NaN,NaN
117714,29/07/2019,131751,644,M,1,0,C,32,ALIMENTOS,HAMBUGUER,NaN,NaN,NaN,NaN
121027,08/05/2019,135222,510,F,4,0,B,87,HIGIENE,PROTETOR SOLAR,NaN,NaN,NaN,NaN
388303,11/12/2020,427786,973,F,4,0,B,45,ALIMENTOS,MANGA,NaN,NaN,NaN,NaN
478914,22/03/2021,527120,947,F,3,1,B,14,ALIMENTOS,BATATA,NaN,NaN,NaN,NaN
447808,02/08/2021,493276,431,F,4,3,B,211,ALIMENTOS,CHA,NaN,NaN,NaN,NaN
293429,20/05/2020,325401,950,M,3,0,C,155,ALIMENTOS,PATE,NaN,NaN,NaN,NaN
80893,24/05/2019,90642,607,F,2,0,B,38,ALIMENTOS,LEITE CONDENSADO,NaN,NaN,NaN,NaN
180678,12/05/2019,204276,160,F,3,4,B,51,ALIMENTOS,PAPINHA INFANTIL,NaN,NaN,NaN,NaN

In [6]:
# Comando  para descobrir o tamanho do DataFrame
df.shape

(830000, 14)

In [7]:
#Comando para identificar principais informações do DataFrame como por exemplo os titos de dados e quantidade de Nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

In [8]:
#Visualizar os tipos de dados de cada coluna
df.dtypes

DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## Limpeza dos Dados e Transformação de dados

In [9]:
#Conforme verificado nos comandos acima, que o DataFrame possui 4 colunas sem nenhum dado, estas serao removidas.

#Exclui as colunas com todas as linhas vazias
df = df.dropna(axis=1, how="all")

#Conferir exclusão das colunas
df

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

In [10]:
#Alteração das Descrições das colunas - Para melhorar legibilidade

df = df.rename(columns= {
    "DATA": "Data",
    "CO_ID":"Compra_ID",
    "CL_ID":"Cliente_ID",
    "CL_GENERO":"Cliente_Genero",
    "CL_EC":"Cliente_Estado_Civil",
    "CL_FHL":"Cliente_Filhos",
    "CL_SEG":"Cliente_Classe",
    "PR_ID":"Produto_ID",
    "PR_CAT":"Produto_Categoria",
    "PR_NOME":"Produto_Nome"

})

print(df)

              Data  Compra_ID  Cliente_ID Cliente_Genero  \
0       01/02/2019       1000         534              M
1       01/02/2019       1000         534              M
2       01/02/2019       1000         534              M
3       01/02/2019       1000         534              M
4       01/02/2019       1000         534              M
...            ...        ...         ...            ...
829995  19/08/2022     919822         155              F
829996  19/08/2022     919822         155              F
829997  19/08/2022     919822         155              F
829998  19/08/2022     919822         155              F
829999  19/08/2022     919822         155              F

        Cliente_Estado_Civil  Cliente_Filhos Cliente_Classe  Produto_ID  \
0                          4               1              C          67
1                          4               1              C          70
2                          4               1              C         178
3                          4               1              C           4
4                          4               1              C         175
...                      ...             ...            ...         ...
829995                     2               0              B         183
829996                     2               0              B          56
829997                     2               0              B         227
829998                     2               0              B         214
829999                     2               0              B          59

       Produto_Categoria          Produto_Nome
0                BEBIDAS  REFRIGERANTE GUARANA
1                BEBIDAS   REFRIGERANTE OUTROS
2                HIGIENE       LENCO UMEDECIDO
3              ALIMENTOS               ABACAXI
4                LIMPEZA     LIMPADOR MULTIUSO
...                  ...                   ...
829995         ALIMENTOS               KETCHUP
829996         ALIMENTOS      QUEIJO MUSSARELA
829997         ALIMENTOS                 ARROZ
829998         ALIMENTOS                CEBOLA
829999         ALIMENTOS            SALGADINHO

[830000 rows x 10 columns]

In [11]:
#Conforme Verificado no comando df.dtypes que a data está como tipo STR devemos altera-la para o tipo Datetime do pandas
df["Data"] = pd.to_datetime(df["Data"], format="%d/%m/%Y")

In [12]:
#Conferindo se alterou para Datetime
print(df["Data"].dtype)

datetime64[us]

In [13]:
#Codigo para verificar todas as colunas que possui tipo de dados como STRING para 
# que elimine espaços em brancos, e coloque o formato para apenas primeira letra maiuscula

colunas_texto = [
    "Cliente_Genero",
    "Cliente_Classe",
    "Produto_Categoria",
    "Produto_Nome"
]

for coluna in colunas_texto:
    df[coluna] = df[coluna].str.strip().str.title()

In [14]:
#Converter para o tipo Numeric do pandas as colunas com dados em formato Inteiro


colunas_inteiras = [
    "Compra_ID",
    "Cliente_ID",
    "Cliente_Filhos",
    "Produto_ID"
]

for coluna in colunas_inteiras:
    df[coluna] = pd.to_numeric(
        df[coluna],
        errors="coerce"
    )

In [15]:
#Troca os Dados da Coluna Cliente_Genero de "F" e "M" para "Feminino" e "Masculino"

df["Cliente_Genero"] = df["Cliente_Genero"].replace({
    "M": "Masculino",
    "F": "Feminino"
})

In [16]:
#Conferindo alteração do dado para não abreviado
df["Cliente_Genero"].value_counts()

Cliente_Genero
Feminino     432576
Masculino    397424
Name: count, dtype: int64

In [17]:
df["Cliente_Estado_Civil"] = df["Cliente_Estado_Civil"].replace({
    1: "Casado/União estável",
    2: "Divorciado",
    3: "Separado",
    4: "Solteiro",
    5: "Viúvo"
}).astype("category")

In [18]:
#Conferindo a alteração para categorias das colunas selecionadas na celula anterior
df.dtypes

Data                    datetime64[us]
Compra_ID                        int64
Cliente_ID                       int64
Cliente_Genero                     str
Cliente_Estado_Civil          category
Cliente_Filhos                   int64
Cliente_Classe                     str
Produto_ID                       int64
Produto_Categoria                  str
Produto_Nome                       str
dtype: object

In [19]:
# Checando se com a conversão dos dados para numeric, nenhum dado ficou como nulo devido um preenchimento errado.
# 

df.isna().sum()

Data                    0
Compra_ID               0
Cliente_ID              0
Cliente_Genero          0
Cliente_Estado_Civil    0
Cliente_Filhos          0
Cliente_Classe          0
Produto_ID              0
Produto_Categoria       0
Produto_Nome            0
dtype: int64

In [20]:
#Separando Ano, Mes e Dia do formato DateTime em Colunas para coletar informaçãos possíveis fornecer futura analise.
df["Ano"] = df["Data"].dt.year
df["Mes"] = df["Data"].dt.month
df["Dia"] = df["Data"].dt.day

In [21]:
#Visualizar novas colunas Ano, Mes e Dia criadas 

df

,Data,Compra_ID,Cliente_ID,Cliente_Genero,Cliente_Estado_Civil,Cliente_Filhos,Cliente_Classe,Produto_ID,Produto_Categoria,Produto_Nome,Ano,Mes,Dia
0,2019-02-01,1000,534,Masculino,Solteiro,1,C,67,Bebidas,Refrigerante Guarana,2019,2,1
1,2019-02-01,1000,534,Masculino,Solteiro,1,C,70,Bebidas,Refrigerante Outros,2019,2,1
2,2019-02-01,1000,534,Masculino,Solteiro,1,C,178,Higiene,Lenco Umedecido,2019,2,1
3,2019-02-01,1000,534,Masculino,Solteiro,1,C,4,Alimentos,Abacaxi,2019,2,1
4,2019-02-01,1000,534,Masculino,Solteiro,1,C,175,Limpeza,Limpador Multiuso,2019,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,2022-08-19,919822,155,Feminino,Divorciado,0,B,183,Alimentos,Ketchup,2022,8,19
829996,2022-08-19,919822,155,Feminino,Divorciado,0,B,56,Alimentos,Queijo Mussarela,2022,8,19
829997,2022-08-19,919822,155,Feminino,Divorciado,0,B,227,Alimentos,Arroz,2022,8,19
829998,2022-08-19,919822,155,Feminino,Divorciado,0,B,214,Alimentos,Cebola,2022,8,19
829999,2022-08-19,919822,155,Feminino,Divorciado,0,B,59,Alimentos,Salgadinho,2022,8,19

#### Tratamento de Dados Invalidos

In [22]:
#Após verificar que existiam preenchimentos com dados e valores invalidos nas Colunas com formato de Dados String. 
# Identifiquei os possíveis preenchimentos errados e inclui uma variável agrupando todos eles.

valores_invalidos = ['#N/D', '#n/d', 'N/A', 'n/a', 'null', 'NULL', '', ' ']


#Codigo que percorre o DataFrame e apresenta as linhas com valores cadatrados como invalidos encontrado em todas as colunas ").

df_invalidos = df[df.isin(valores_invalidos).any(axis=1)]

#Apresenta as linhas com dados invalidos.
print(df_invalidos)

             Data  Compra_ID  Cliente_ID Cliente_Genero  Cliente_Estado_Civil  \
82     2019-02-01       1078         290       Feminino  Casado/União estável
223    2019-02-01       1103         957      Masculino            Divorciado
640    2019-02-01       1482         453       Feminino  Casado/União estável
857    2019-02-01       1683         438       Feminino  Casado/União estável
917    2019-02-01       1793         608       Feminino              Separado
...           ...        ...         ...            ...                   ...
829528 2022-08-19     919578         567       Feminino  Casado/União estável
829602 2022-08-19     919626         758       Feminino              Separado
829787 2022-08-19     919716         801      Masculino  Casado/União estável
829829 2022-08-19     919716         801      Masculino  Casado/União estável
829882 2022-08-19     919770         888       Feminino              Solteiro

        Cliente_Filhos Cliente_Classe  Produto_ID Produto_Categoria  \
82                   0              B         107              #N/D
223                  3              B         107              #N/D
640                  0              B         107              #N/D
857                  0              B         107              #N/D
917                  0              C         107              #N/D
...                ...            ...         ...               ...
829528               0              C         107              #N/D
829602               0              B         107              #N/D
829787               4              B         107              #N/D
829829               4              B         107              #N/D
829882               2              B         107              #N/D

       Produto_Nome   Ano  Mes  Dia
82             #N/D  2019    2    1
223            #N/D  2019    2    1
640            #N/D  2019    2    1
857            #N/D  2019    2    1
917            #N/D  2019    2    1
...             ...   ...  ...  ...
829528         #N/D  2022    8   19
829602         #N/D  2022    8   19
829787         #N/D  2022    8   19
829829         #N/D  2022    8   19
829882         #N/D  2022    8   19

[3650 rows x 13 columns]

In [23]:
#Verificado que as colunas "Produto_Categoria" e "Produto_Nome" possuiam preenchimentos com os dados invalidos cadastrados na variavel "valores_invalidos"

#Tramento dos invalidos na coluna "PR_CAT" para um Descritivo que possa ser computado na analise.
df["Produto_Categoria"] = df["Produto_Categoria"].apply(
    lambda x: 'Sem Categoria' if pd.isna(x) or str(x) in valores_invalidos else x
)

#Confirmar tratamento dos dados invalidos
categoria_desconhecida = df[df["Produto_Categoria"] == "Sem Categoria"]
print(categoria_desconhecida)

             Data  Compra_ID  Cliente_ID Cliente_Genero  Cliente_Estado_Civil  \
82     2019-02-01       1078         290       Feminino  Casado/União estável
223    2019-02-01       1103         957      Masculino            Divorciado
640    2019-02-01       1482         453       Feminino  Casado/União estável
857    2019-02-01       1683         438       Feminino  Casado/União estável
917    2019-02-01       1793         608       Feminino              Separado
...           ...        ...         ...            ...                   ...
829528 2022-08-19     919578         567       Feminino  Casado/União estável
829602 2022-08-19     919626         758       Feminino              Separado
829787 2022-08-19     919716         801      Masculino  Casado/União estável
829829 2022-08-19     919716         801      Masculino  Casado/União estável
829882 2022-08-19     919770         888       Feminino              Solteiro

        Cliente_Filhos Cliente_Classe  Produto_ID Produto_Categoria  \
82                   0              B         107     Sem Categoria
223                  3              B         107     Sem Categoria
640                  0              B         107     Sem Categoria
857                  0              B         107     Sem Categoria
917                  0              C         107     Sem Categoria
...                ...            ...         ...               ...
829528               0              C         107     Sem Categoria
829602               0              B         107     Sem Categoria
829787               4              B         107     Sem Categoria
829829               4              B         107     Sem Categoria
829882               2              B         107     Sem Categoria

       Produto_Nome   Ano  Mes  Dia
82             #N/D  2019    2    1
223            #N/D  2019    2    1
640            #N/D  2019    2    1
857            #N/D  2019    2    1
917            #N/D  2019    2    1
...             ...   ...  ...  ...
829528         #N/D  2022    8   19
829602         #N/D  2022    8   19
829787         #N/D  2022    8   19
829829         #N/D  2022    8   19
829882         #N/D  2022    8   19

[3650 rows x 13 columns]

In [24]:
#Tramento dos invalidos na coluna "Produto_Nome" para um descritivo que possa ser computado na analise.
df["Produto_Nome"] = df["Produto_Nome"].apply(
    lambda x: 'Produto não cadastrado' if pd.isna(x) or str(x) in valores_invalidos else x
)

#Confirmar tratamento dos dados invalidos
produto_nao_cadastrado = df[df["Produto_Nome"] == "Produto não cadastrado"]
print(produto_nao_cadastrado)

             Data  Compra_ID  Cliente_ID Cliente_Genero  Cliente_Estado_Civil  \
82     2019-02-01       1078         290       Feminino  Casado/União estável
223    2019-02-01       1103         957      Masculino            Divorciado
640    2019-02-01       1482         453       Feminino  Casado/União estável
857    2019-02-01       1683         438       Feminino  Casado/União estável
917    2019-02-01       1793         608       Feminino              Separado
...           ...        ...         ...            ...                   ...
829528 2022-08-19     919578         567       Feminino  Casado/União estável
829602 2022-08-19     919626         758       Feminino              Separado
829787 2022-08-19     919716         801      Masculino  Casado/União estável
829829 2022-08-19     919716         801      Masculino  Casado/União estável
829882 2022-08-19     919770         888       Feminino              Solteiro

        Cliente_Filhos Cliente_Classe  Produto_ID Produto_Categoria  \
82                   0              B         107     Sem Categoria
223                  3              B         107     Sem Categoria
640                  0              B         107     Sem Categoria
857                  0              B         107     Sem Categoria
917                  0              C         107     Sem Categoria
...                ...            ...         ...               ...
829528               0              C         107     Sem Categoria
829602               0              B         107     Sem Categoria
829787               4              B         107     Sem Categoria
829829               4              B         107     Sem Categoria
829882               2              B         107     Sem Categoria

                  Produto_Nome   Ano  Mes  Dia
82      Produto não cadastrado  2019    2    1
223     Produto não cadastrado  2019    2    1
640     Produto não cadastrado  2019    2    1
857     Produto não cadastrado  2019    2    1
917     Produto não cadastrado  2019    2    1
...                        ...   ...  ...  ...
829528  Produto não cadastrado  2022    8   19
829602  Produto não cadastrado  2022    8   19
829787  Produto não cadastrado  2022    8   19
829829  Produto não cadastrado  2022    8   19
829882  Produto não cadastrado  2022    8   19

[3650 rows x 13 columns]

In [25]:
#Conferindo que o Produto ID 107 - Identificado anteriormente como sem preenchimento estão preenchidos com os dados tratados
df[df["Produto_ID"] == 107]

,Data,Compra_ID,Cliente_ID,Cliente_Genero,Cliente_Estado_Civil,Cliente_Filhos,Cliente_Classe,Produto_ID,Produto_Categoria,Produto_Nome,Ano,Mes,Dia
82,2019-02-01,1078,290,Feminino,Casado/União estável,0,B,107,Sem Categoria,Produto não cadastrado,2019,2,1
223,2019-02-01,1103,957,Masculino,Divorciado,3,B,107,Sem Categoria,Produto não cadastrado,2019,2,1
640,2019-02-01,1482,453,Feminino,Casado/União estável,0,B,107,Sem Categoria,Produto não cadastrado,2019,2,1
857,2019-02-01,1683,438,Feminino,Casado/União estável,0,B,107,Sem Categoria,Produto não cadastrado,2019,2,1
917,2019-02-01,1793,608,Feminino,Separado,0,C,107,Sem Categoria,Produto não cadastrado,2019,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829528,2022-08-19,919578,567,Feminino,Casado/União estável,0,C,107,Sem Categoria,Produto não cadastrado,2022,8,19
829602,2022-08-19,919626,758,Feminino,Separado,0,B,107,Sem Categoria,Produto não cadastrado,2022,8,19
829787,2022-08-19,919716,801,Masculino,Casado/União estável,4,B,107,Sem Categoria,Produto não cadastrado,2022,8,19
829829,2022-08-19,919716,801,Masculino,Casado/União estável,4,B,107,Sem Categoria,Produto não cadastrado,2022,8,19
829882,2022-08-19,919770,888,Feminino,Solteiro,2,B,107,Sem Categoria,Produto não cadastrado,2022,8,19

In [26]:
#Confirmando que todos os valores nulos foram alterados para Não informado ou Produto não cadastrado. Resultado deve apresentar todas as colunas com 0
df.isna().sum()

Data                    0
Compra_ID               0
Cliente_ID              0
Cliente_Genero          0
Cliente_Estado_Civil    0
Cliente_Filhos          0
Cliente_Classe          0
Produto_ID              0
Produto_Categoria       0
Produto_Nome            0
Ano                     0
Mes                     0
Dia                     0
dtype: int64

In [27]:
### Transformandos as colunas em categorias.
df["Cliente_Genero"] = df["Cliente_Genero"].astype("category")
df["Cliente_Estado_Civil"] = df["Cliente_Estado_Civil"].astype("category")
df["Cliente_Classe"] = df["Cliente_Classe"].astype("category")
df["Produto_Categoria"] = df["Produto_Categoria"].astype("category")

#### Dados Duplicados (Optado por ignorar)

In [28]:
#Comando para verificar em todo o DataFrame se possui preencimento com linhas duplicadas, 
# Como se trata de uma Tabela onde não contabiliza quantidade de itens, não significa necessáriamente que 
# os dados duplicados estão errados,  o cliente pode ter comprado duas vezes o mesmo produto por exemplo.

df.duplicated().sum()

np.int64(96553)

In [29]:
#Comando para apresentar as linhas duplicadas.
#Podemos veriricar ao executar que na coluna de Nome dos produtos são produtos que podem haver mais do que uma compra, justificando a não exclusão.
df[df.duplicated()]

,Data,Compra_ID,Cliente_ID,Cliente_Genero,Cliente_Estado_Civil,Cliente_Filhos,Cliente_Classe,Produto_ID,Produto_Categoria,Produto_Nome,Ano,Mes,Dia
19,2019-02-01,1000,534,Masculino,Solteiro,1,C,13,Alimentos,Banana,2019,2,1
40,2019-02-01,1000,534,Masculino,Solteiro,1,C,4,Alimentos,Abacaxi,2019,2,1
46,2019-02-01,1000,534,Masculino,Solteiro,1,C,11,Alimentos,Azeite,2019,2,1
49,2019-02-01,1000,534,Masculino,Solteiro,1,C,69,Bebidas,Refrigerante Limao,2019,2,1
50,2019-02-01,1000,534,Masculino,Solteiro,1,C,218,Alimentos,Bife De Coxao Mole,2019,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,2022-08-19,919822,155,Feminino,Divorciado,0,B,34,Alimentos,Ketchup,2022,8,19
829992,2022-08-19,919822,155,Feminino,Divorciado,0,B,30,Alimentos,File De Peixe,2022,8,19
829995,2022-08-19,919822,155,Feminino,Divorciado,0,B,183,Alimentos,Ketchup,2022,8,19
829996,2022-08-19,919822,155,Feminino,Divorciado,0,B,56,Alimentos,Queijo Mussarela,2022,8,19
829997,2022-08-19,919822,155,Feminino,Divorciado,0,B,227,Alimentos,Arroz,2022,8,19

In [30]:
### Verificando Possíveis OutLiers nos dados de filhos. Para Garantir que alguem não digitou um numero erroneamente e quebre o contexto da analise.

Q1 = df["Cliente_Filhos"].quantile(0.25)
Q3 = df["Cliente_Filhos"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = 0
limite_superior = Q3 + 1.5 * IQR


print(limite_inferior)
print(limite_superior)


outliers = df[
    (df["Cliente_Filhos"] < limite_inferior) |
    (df["Cliente_Filhos"] > limite_superior) 
]

outliers

0
5.0

Empty DataFrame
Columns: [Data, Compra_ID, Cliente_ID, Cliente_Genero, Cliente_Estado_Civil, Cliente_Filhos, Cliente_Classe, Produto_ID, Produto_Categoria, Produto_Nome, Ano, Mes, Dia]
Index: []

## Analises e Estatisticas

In [31]:
#Quantidades de Compras cadastradas - Incluindo todos os Itens no mesmo Id de Compra

quantidade_compras = df["Compra_ID"].nunique()

print(f"Quantidade de compras únicas: {quantidade_compras}")

Quantidade de compras únicas: 18471

In [32]:
filhos = df["Cliente_Filhos"]

print("\n===== ESTATÍSTICA DESCRITIVA =====")

print(f"Contagem: {filhos.count()}")
print(f"Média: {filhos.mean():.2f}")
print(f"Mediana: {filhos.median():.2f}")
print(f"Desvio padrão: {filhos.std():.2f}")
print(f"Máximo: {filhos.max()}")
print(f"Mínimo: {filhos.min()}")

===== ESTATÍSTICA DESCRITIVA =====
Contagem: 830000
Média: 1.15
Mediana: 0.00
Desvio padrão: 1.42
Máximo: 4
Mínimo: 0

In [33]:
print(df.groupby("Cliente_Genero").size())

Cliente_Genero
Feminino     432576
Masculino    397424
dtype: int64

In [34]:
## Percentual de Compras Masculino e Feminino

percentual = df["Cliente_Genero"].value_counts(normalize=True) * 100

print(f"Feminino: {percentual['Feminino']:.2f}%")
print(f"Masculino: {percentual['Masculino']:.2f}%")

Feminino: 52.12%
Masculino: 47.88%

In [35]:
# Quantidade de vendas por Categoria;
vendas_categoria = (
    df.groupby("Produto_Categoria")
      .size()
      .sort_values(ascending=False)
)

print("\n===== REGISTROS POR CATEGORIA =====")
print(vendas_categoria)

===== REGISTROS POR CATEGORIA =====
Produto_Categoria
Alimentos        434767
Higiene          155574
Limpeza          145754
Bebidas           43299
Pet               32399
Acessorios        14557
Sem Categoria      3650
dtype: int64

In [36]:
vendas_produto = (df.groupby("Produto_Nome")
      .size()
      .sort_values(ascending=False)
)

print("\n===== REGISTROS POR CATEGORIA =====")
print(vendas_produto)

===== REGISTROS POR CATEGORIA =====
Produto_Nome
Presunto Cozido           14381
Sardinha                   7490
Gel                        7399
Banana                     7385
Desengordurante            7378
                          ...
Produto não cadastrado     3650
Absorvente                 3639
Alcool                     3611
Alimento Para Passaro      3605
Alho                       3574
Length: 118, dtype: int64

In [37]:
# Agrupamento por Genero e Produto - Não percebeu-se tendencia de um genero ter preferencia por alguma categoria que se destaque.
genero_categoria = (df.groupby([
        "Cliente_Genero",
        "Produto_Categoria"
    ])
    .size()
    .sort_values(ascending=False)
)

print("\n===== GÊNERO X CATEGORIA =====")
print(genero_categoria)

===== GÊNERO X CATEGORIA =====
Cliente_Genero  Produto_Categoria
Feminino        Alimentos            226575
Masculino       Alimentos            208192
Feminino        Higiene               80991
                Limpeza               76298
Masculino       Higiene               74583
                Limpeza               69456
Feminino        Bebidas               22345
Masculino       Bebidas               20954
Feminino        Pet                   16749
Masculino       Pet                   15650
Feminino        Acessorios             7700
Masculino       Acessorios             6857
Feminino        Sem Categoria          1918
Masculino       Sem Categoria          1732
dtype: int64

In [38]:
df.groupby(["Ano"]).size().sort_values(ascending=False)

Ano
2021    245259
2020    218367
2019    199036
2022    167338
dtype: int64

In [39]:
df.groupby(["Mes"]).size().sort_values(ascending=False)

Mes
1     83963
5     82275
2     76201
10    73900
12    70449
7     68983
9     68594
6     67808
4     66935
8     65609
3     64371
11    40912
dtype: int64

## Exportação do DataFrame Limpo para um Novo CSV

In [40]:
df.to_csv(
    "base_varejo_atualizada.csv",
    sep=",",
    index=False,
    encoding="utf-8-sig"
)